Repository Leantime/leantime, pull requests merged in 2023-10, with the labels that each got.

#1982 Bug fixes
  app/Core/Template.php
  app/Domain/Canvas/Services/Canvas.php
  app/Domain/Canvas/Templates/canvasDialog.inc.php
  app/Domain/Cron/Services/Cron.php
  app/Domain/Files/Templates/submodules/showAll.sub.php
  app/Domain/Goalcanvas/Templates/canvasDialog.tpl.php
  app/Domain/Ideas/Templates/ideaDialog.tpl.php
  app/Domain/Menu/Composers/Menu.php
  app/Domain/Tickets/Controllers/NewTicket.php
  app/Domain/Tickets/Repositories/Tickets.php
  app/Domain/Users/Repositories/Users.php
  app/Domain/Valuecanvas/Templates/canvasDialog.tpl.php
  public/assets/css/components/mobile.css
Labels: Bug

#1990 Fix: canvas repository not found on blueprints
  app/Domain/Canvas/Services/Canvas.php
Labels: Bug

#2001 Update pl-PL.ini
  app/Language/pl-PL.ini
Labels: hacktoberfest-accepted

#1966 make template for mailer filterable, rather than the entire contents …
  app/Core/Mailer.php
  app/Core/Template.php
Labels: Feature, Breaking-Change
